# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Comprehensive/OSX/OSX.cache/wt [current_project]
set_property parent.project_path C:/Comprehensive/OSX/OSX.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Comprehensive/OSX/OSX.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_const.vh
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_config.vh
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dsp_const.vh
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mmu.vh
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mipsfpga_ahb_const.vh
}
read_verilog -library xil_defaultlib {
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/RAMB4K_S16.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/RAMB4K_S2.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/RAMB4K_S8.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/d_wsram_2k2way_xilinx.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/dataram_2k2way_xilinx.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/ejtag_reset.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/i_wsram_2k2way_xilinx.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_alu_dsp_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_alu_shft_32bit.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_bistctl.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_biu.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cache_cmp.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cache_mux.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cdmmstub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_clock_buf.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_clock_nogate.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_clockandlatch.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_clockxnorgate.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cop1_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cop2_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_core.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cp1_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cp2_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpu.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_antitamper_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_eicoffset_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_guest_srs1.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_guest_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_pc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_pc_top.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_prid.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_root_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_sps_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_srs1.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cpz_watch_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cscramble_scanio_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cscramble_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_cscramble_tpl.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dc_bistctl.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dcc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dcc_fb.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dcc_mb_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dcc_parity_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dcc_spmb_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dcc_spstub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_dspram_ext_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_edp.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_edp_add_simple.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_edp_buf_misc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_edp_clz.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_edp_clz_16b.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_edp_clz_4b.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_and2.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_area.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_async_rec.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_async_snd.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_brk21.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_bus32mux2.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_dbrk.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_gate.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_ibrk.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_mux2.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_pdttcb_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_tap.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_tap_dasamstub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_tap_fdcstub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_tap_pcsamstub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ejt_tck.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_fpuclk1_nogate.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_gf_mux2.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_glue.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ic.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ic_bistctl.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_icc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_icc_mb_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_icc_parity_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_icc_spmb_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_icc_spstub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_icc_umips_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_ispram_ext_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mdl.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mdl_add_simple.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mdl_ctl.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mdl_dp.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mmuc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mpc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mpc_ctl.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mpc_dec.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_mpc_exc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_rf_reg.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_rf_rngc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_rf_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_siu.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_siu_int_sync.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_spram_top.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_collector.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_cpy.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_ctl.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_dtlb.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_itlb.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_jtlb16.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_jtlb16entries.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_jtlb1entry.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_jtlb4entries.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_utlb.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_tlb_utlbentry.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_top.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/m14k_udi_stub.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mipsfpga_ahb.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mipsfpga_ahb_gpio.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mipsfpga_ahb_ram.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mipsfpga_ahb_ram_reset.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mipsfpga_sys.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_cregister.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_cregister_c.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_cregister_ngc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_cregister_s.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_cregister_wide.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_cregister_wide_tlb.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_cregister_wide_utlb.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_latchn.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux16.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_10.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_13.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_24.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_3.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_4.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_5.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_6.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_8.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux1hot_9.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux2.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux4.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_mux8.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_register.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_register_c.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_register_ngc.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_register_s.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mvp_ucregister_wide.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/ram_dual_port.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/ram_reset_dual_port.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/tagram_2k2way_xilinx.v
  C:/Comprehensive/OSX/OSX.srcs/sources_1/imports/rtl_up/mipsfpga_nexys4_ddr.v
}
read_ip -quiet c:/Comprehensive/OSX/OSX.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Comprehensive/OSX/OSX.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Comprehensive/OSX/OSX.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Comprehensive/OSX/OSX.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Comprehensive/OSX/OSX.srcs/constrs_1/imports/Lab01_Vivado/mipsfpga_nexys4_ddr.xdc
set_property used_in_implementation false [get_files C:/Comprehensive/OSX/OSX.srcs/constrs_1/imports/Lab01_Vivado/mipsfpga_nexys4_ddr.xdc]


synth_design -top mipsfpga_nexys4_ddr -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mipsfpga_nexys4_ddr.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mipsfpga_nexys4_ddr_utilization_synth.rpt -pb mipsfpga_nexys4_ddr_utilization_synth.pb"
